# Generated by Django 5.1.1 on 2024-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видеокарты')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=512)),
            ],
        ),
    ]
