# Generated by Django 5.1.1 on 2024-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='image',
            field=models.ImageField(upload_to='resources/'),
        ),
    ]
