# Generated by Django 5.1.1 on 2024-10-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='gpu',
            new_name='gpu',
        ),
    ]
